// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3rRBPnzn6Fjbjka5JxvX23m5dAb0c12I',
    appId: '1:116787073632:web:077f5e4648e2a4c647a905',
    messagingSenderId: '116787073632',
    projectId: 'reminder-app-87da4',
    authDomain: 'reminder-app-87da4.firebaseapp.com',
    storageBucket: 'reminder-app-87da4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWkJbB3qijZ5Mf7U94JoLTyZGQwZweEBE',
    appId: '1:116787073632:android:f1efa661556e33e647a905',
    messagingSenderId: '116787073632',
    projectId: 'reminder-app-87da4',
    storageBucket: 'reminder-app-87da4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4gAyOBSjVsDxRirWoihekQ-lSCoJdExs',
    appId: '1:116787073632:ios:fa6439b1cf80318e47a905',
    messagingSenderId: '116787073632',
    projectId: 'reminder-app-87da4',
    storageBucket: 'reminder-app-87da4.appspot.com',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4gAyOBSjVsDxRirWoihekQ-lSCoJdExs',
    appId: '1:116787073632:ios:c013cbb10e2c26f847a905',
    messagingSenderId: '116787073632',
    projectId: 'reminder-app-87da4',
    storageBucket: 'reminder-app-87da4.appspot.com',
    iosBundleId: 'com.example.reminderApp.RunnerTests',
  );
}
